// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Category struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	Wallpapers []*Wallpaper `json:"wallpapers"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewWallpaper struct {
	Title             string   `json:"title"`
	Description       *string  `json:"description,omitempty"`
	LightWallpaperURL string   `json:"lightWallpaperUrl"`
	DarkWallpaperURL  string   `json:"darkWallpaperUrl"`
	CategoryID        *string  `json:"categoryId,omitempty"`
	TagsIds           []string `json:"tagsIds,omitempty"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Tag struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	Wallpapers []*Wallpaper `json:"wallpapers"`
}

type User struct {
	ID         string       `json:"id"`
	Username   string       `json:"username"`
	CreatedAt  time.Time    `json:"createdAt"`
	Wallpapers []*Wallpaper `json:"wallpapers"`
	Favorites  []*Wallpaper `json:"favorites"`
}

type Wallpaper struct {
	ID                string     `json:"id"`
	Title             string     `json:"title"`
	Description       *string    `json:"description,omitempty"`
	LightWallpaperURL string     `json:"lightWallpaperUrl"`
	DarkWallpaperURL  string     `json:"darkWallpaperUrl"`
	Author            *User      `json:"author"`
	Category          *Category  `json:"category,omitempty"`
	Tags              []*Tag     `json:"tags"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         *time.Time `json:"UpdatedAt,omitempty"`
	DownloadCount     int        `json:"downloadCount"`
	ViewCount         int        `json:"viewCount"`
	FavoriteCount     int        `json:"favoriteCount"`
}
